spring:
  profiles: dev

  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://139.224.135.139:3306/garbage?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: "root"
    password: "045135127."
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
