
spring:
  profiles:
    active: dev
  application:
    name: workflow-engine

#common config
deploy:
  version: 1.0.0

#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8081
logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error
